data = [
    {"FullName": "Alejandro Monteón", "Region": "LMM 1"},
    {"FullName": "Cynthia Pérez", "Region": "LMM 1"},
    {"FullName": "Ignacio García Plaisant", "Region": "LMM 1"},
    {"FullName": "Juan Villaseñor", "Region": "LMM 1"},
    {"FullName": "Gerardo Vazquez", "Region": "LMM 1"},
    {"FullName": "Carlos Ramos", "Region": "LMM 1"},
    {"FullName": "Ricardo Lomeli", "Region": "LMM 1"},
    {"FullName": "Jesus Albarran", "Region": "LMM 1"},
    {"FullName": "Emilio Ojeda", "Region": "LMM 2"},
    {"FullName": "Fernando Cruz", "Region": "LMM 2"},
    {"FullName": "Jose Nava", "Region": "LMM 2"},
    {"FullName": "Prizila Ramos", "Region": "LMM 2"},
    {"FullName": "Julieta Medrano", "Region": "LMM 2"},
    {"FullName": "Jeudiel Zamudio", "Region": "LMM 2"},
    {"FullName": "Maria de los Angeles Fonseca", "Region": "LMM 2"},
    {"FullName": "Teresa Cisneros", "Region": "LMM 3"},
    {"FullName": "Diego Trevilla", "Region": "LMM 3"},
    {"FullName": "Diego Aviña", "Region": "LMM 3"},
    {"FullName": "Ramón Pérez", "Region": "LMM 3"},
    {"FullName": "Edson Flores", "Region": "LMM 3"},
    {"FullName": "Jacobo Frontana", "Region": "LMM 3"},
    {"FullName": "Yunuen de la Cruz", "Region": "LMM 3"},
    {"FullName": "Alexandra Ramírez", "Region": "LMM 4"},
    {"FullName": "Myrna Leija", "Region": "LMM 4"},
    {"FullName": "Erick Perez", "Region": "LMM 4"},
    {"FullName": "Alexandra Luna", "Region": "LMM 4"},
    {"FullName": "Mayreth García", "Region": "LMM 4"},
    {"FullName": "Abierta", "Region": "LMM 4"},
    {"FullName": "Manuel Vargas", "Region": "LMM 4"},
    {"FullName": "Moises Villalon", "Region": "LMM 5"},
    {"FullName": "Monserrat Villanueva", "Region": "LMM 5"},
    {"FullName": "Jorge Avendaño", "Region": "LMM 5"},
    {"FullName": "Eduardo Martinez", "Region": "LMM 5"},
    {"FullName": "Oscar Ordaz", "Region": "LMM 5"},
    {"FullName": "Gabriel Zaldivar", "Region": "LMM 5"},
    {"FullName": "Yenisei Garcia", "Region": "Capital Markets"},
    {"FullName": "Herbert Bouchez", "Region": "Capital Markets"},
    {"FullName": "Alvaro de Garay", "Region": "Capital Markets"},
    {"FullName": "Dulce Villegas", "Region": "Guadalajara"},
    {"FullName": "Samuel Cepeda", "Region": "Guadalajara"},
    {"FullName": "Omar Rodríguez", "Region": "Guadalajara"},
    {"FullName": "Daniel Castillo", "Region": "Guadalajara"},
    {"FullName": "Natalia Bernat", "Region": "Guadalajara"},
    {"FullName": "Fernando Carbajal", "Region": "Guadalajara"},
    {"FullName": "Miguel Ortiz", "Region": "Guadalajara"},
    {"FullName": "Mario Vázquez", "Region": "Guadalajara"},
    {"FullName": "Agustin Ruiz", "Region": "México 1"},
    {"FullName": "Alejandro Trujillo", "Region": "México 1"},
    {"FullName": "Edith Sánchez", "Region": "México 1"},
    {"FullName": "Alejandro Karam", "Region": "México 1"},
    {"FullName": "Laura Villagomez", "Region": "México 1"},
    {"FullName": "Pablo Casellas", "Region": "México 1"},
    {"FullName": "Rafael Garcia", "Region": "México 2"},
    {"FullName": "Octavio Chimal", "Region": "México 2"},
    {"FullName": "Hernan Aguilar", "Region": "México 2"},
    {"FullName": "Federico Carreón", "Region": "México 2"},
    {"FullName": "Marco Cohen", "Region": "México 2"},
    {"FullName": "Juan Pablo Mendieta", "Region": "México 2"},
    {"FullName": "Vianney Vallejo", "Region": "México 3"},
    {"FullName": "Enrique Luna", "Region": "México 3"},
    {"FullName": "Abierta", "Region": "México 3"},
    {"FullName": "Abierta", "Region": "México 3"},
    {"FullName": "Mario Garcia", "Region": "México 3"},
    {"FullName": "Juan Carlos Castillo", "Region": "México 3"},
    {"FullName": "Dario del Río", "Region": "Monterrey"},
    {"FullName": "Miguel Antunez", "Region": "Monterrey"},
    {"FullName": "Carlos Garmilla", "Region": "Monterrey"},
    {"FullName": "Arantza Solbes", "Region": "Monterrey"},
    {"FullName": "Juan Edgar Zepeda", "Region": "Monterrey"},
    {"FullName": "Sergio Mange", "Region": "Monterrey"},
    {"FullName": "Ricardo Meza", "Region": "Monterrey"},
    {"FullName": "Jr. Abierta", "Region": "Monterrey"},
    {"FullName": "Eduardo Garcia Conde", "Region": "Monterrey & IMMEX"},
    {"FullName": "Marianna Peña", "Region": "SWATT LMM 1"},
    {"FullName": "Miriam Martinez", "Region": "SWATT LMM 1"},
    {"FullName": "Manuel Ibal", "Region": "SWATT LMM 1"},
    {"FullName": "Nueva Hunter Jr.", "Region": "SWATT LMM 1"},
    {"FullName": "Fernando Perez", "Region": "SWATT LMM 2"},
    {"FullName": "Miguel Rivera", "Region": "SWATT LMM 2"},
    {"FullName": "Cynthia Diaz", "Region": "SWATT LMM 2"},
    {"FullName": "Roberto Zacatento", "Region": "LMM SWATT"},
    {"FullName": "Jaime Guzmán", "Region": "Vendor"},
    {"FullName": "José Bustos", "Region": "Vendor"},
    {"FullName": "Rene Lopez", "Region": "Vendor"},
    {"FullName": "Marco Ibarra", "Region": "Energía"},
    {"FullName": "Alejandro Solorzano", "Region": "Vendor & Energy"},
]